# Site
name: "Recipes With Gare"
description: "Easy, Simple And Delicious Recipes"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "gare@gareville.com"
mailchimp-list: ""

include: ["_pages"]
permalink: /:title/
url: "https://www.thefresh.co.zm"
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  gare:
    name: Gare
    site: https://www.garville.com
    avatar: /assets/images/avatar2.jpg
    bio: "Hi, welcome to my food blog. These are simple yet delicious recipes I have picked up over the years. I love everyone of them and it's my pleasure to share them with you. See something you like ? Try it out and let me know how it turns out."
    email: gare@gareville.com
    twitter: https://twitter.com

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: gare
      avatar: /assets/images/avatar2.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
